import type { GeneratedTestCase, RequestConfig } from "./types";

function jsonLiteral(v: unknown): string {
  return JSON.stringify(v, null, 2);
}

function buildHeadersObject(config: RequestConfig): Record<string, string> {
  const out: Record<string, string> = { "Content-Type": "application/json" };
  for (const h of config.headers) {
    if (h.enabled && h.key.trim()) out[h.key.trim()] = h.value;
  }
  return out;
}

export function buildSpecFile(config: RequestConfig, cases: GeneratedTestCase[]): string {
  const enabled = cases.filter(c => c.enabled);
  const headers = buildHeadersObject(config);
  const tokenEnv = config.auth.envVarName || "API_TOKEN";
  const useEnvToken = config.auth.mode === "envBearer" || config.auth.mode === "staticBearer";

  let basePayload: unknown = {};
  try {
    basePayload = JSON.parse(config.bodyJson || "{}");
  } catch {
    basePayload = {};
  }

  const sanitizedCases = enabled.map(c => ({
    id: c.id,
    name: c.name,
    category: c.category,
    fieldPath: c.fieldPath ?? null,
    override: c.override ?? null,
    removePaths: c.removePaths ?? [],
    headersOverride: c.headersOverride ?? null,
    expectedStatus: c.expectedStatus,
    risk: c.risk,
    reason: c.reason,
  }));

  return `/**
 * ${config.apiName || "Generated API"} — Playwright API tests
 * Auto-generated by API TestForge.
 *
 * Drop this file into any Playwright TypeScript project:
 *   tests/${(config.apiName || "api").toLowerCase().replace(/\\s+/g, "-")}.spec.ts
 *
 * Required env vars:
 *   BASE_URL=${config.baseUrl}
${useEnvToken ? `*   ${tokenEnv}=your_token_here\n` : ""} */
import { test, expect, request as pwRequest } from "@playwright/test";
import * as fs from "fs";
import * as path from "path";
import "dotenv/config";

// ---------- Config ----------
const BASE_URL = process.env.BASE_URL || ${JSON.stringify(config.baseUrl)};
const ENDPOINT = ${JSON.stringify(config.endpoint)};
const METHOD = ${JSON.stringify(config.method)} as const;
const SUCCESS_STATUS = ${config.expectedSuccessStatus};
const VALIDATION_STATUS = ${config.expectedValidationStatus};

const BASE_HEADERS: Record<string, string> = ${jsonLiteral(headers)};

const BASE_PAYLOAD: Record<string, unknown> = ${jsonLiteral(basePayload)};

interface TestCase {
  id: string;
  name: string;
  category: string;
  fieldPath: string | null;
  override: Record<string, unknown> | null;
  removePaths: string[];
  headersOverride: Record<string, string | null> | null;
  expectedStatus: number;
  risk: "low" | "medium" | "high";
  reason: string;
}

const CASES: TestCase[] = ${jsonLiteral(sanitizedCases)};

// ---------- Helpers ----------
function deepClone<T>(v: T): T {
  return JSON.parse(JSON.stringify(v));
}

function setByPath(obj: any, dotPath: string, value: unknown): void {
  const parts = dotPath.split(".");
  let cur = obj;
  for (let i = 0; i < parts.length - 1; i++) {
    if (cur[parts[i]] == null || typeof cur[parts[i]] !== "object") cur[parts[i]] = {};
    cur = cur[parts[i]];
  }
  cur[parts[parts.length - 1]] = value;
}

function deleteByPath(obj: any, dotPath: string): void {
  const parts = dotPath.split(".");
  let cur = obj;
  for (let i = 0; i < parts.length - 1; i++) {
    if (cur[parts[i]] == null) return;
    cur = cur[parts[i]];
  }
  delete cur[parts[parts.length - 1]];
}

function buildPayload(tc: TestCase): unknown {
  const payload = deepClone(BASE_PAYLOAD);
  for (const p of tc.removePaths) deleteByPath(payload, p);
  if (tc.override) {
    for (const [k, v] of Object.entries(tc.override)) {
      if (k.includes(".")) setByPath(payload, k, v);
      else (payload as any)[k] = v;
    }
  }
  return payload;
}

function applyHeadersOverride(tc: TestCase): Record<string, string> {
  const headers = { ...BASE_HEADERS };
${useEnvToken ? `  const token = process.env.${tokenEnv};\n  if (token) headers["Authorization"] = \`Bearer \${token}\`;\n` : ""}  if (tc.headersOverride) {
    for (const [k, v] of Object.entries(tc.headersOverride)) {
      if (v === null) delete headers[k];
      else headers[k] = v;
    }
  }
  return headers;
}

function classifyResponse(status: number, expected: number): "pass" | "fail" {
  return status === expected ? "pass" : "fail";
}

interface CaseResult {
  id: string;
  name: string;
  category: string;
  expectedStatus: number;
  actualStatus: number;
  result: "pass" | "fail";
  risk: string;
  reason: string;
  request: {
    method: string;
    url: string;
    headers: Record<string, string>;
    body: unknown;
  };
  response: {
    status: number;
    headers: Record<string, string>;
    body: unknown;
  };
}
const results: CaseResult[] = [];

function safeParse(text: string): unknown {
  try { return JSON.parse(text); } catch { return text; }
}

function redactHeaders(h: Record<string, string>): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(h)) {
    if (/^authorization$|api[-_]?key|token|secret|cookie/i.test(k)) {
      out[k] = v ? "***redacted***" : v;
    } else {
      out[k] = v;
    }
  }
  return out;
}

// ---------- Tests ----------
test.describe(${JSON.stringify(config.apiName || "API tests")}, () => {
  for (const tc of CASES) {
    test(\`[\${tc.category}] \${tc.name}\`, async (testInfo) => {
      const ctx = await pwRequest.newContext({ baseURL: BASE_URL });
      const headers = applyHeadersOverride(tc);
      const payload = buildPayload(tc);
      const requestBody = METHOD === "GET" ? undefined : payload;

      // Attach request payload to the Playwright HTML report
      await testInfo.attach("request.json", {
        body: JSON.stringify({
          method: METHOD,
          url: \`\${BASE_URL}\${ENDPOINT}\`,
          headers: redactHeaders(headers),
          body: requestBody ?? null,
        }, null, 2),
        contentType: "application/json",
      });

      const response = await ctx.fetch(ENDPOINT, {
        method: METHOD,
        headers,
        data: requestBody,
      });

      const actual = response.status();
      const respText = await response.text();
      const respBody = safeParse(respText);
      const respHeaders = response.headers();

      // Attach response payload to the Playwright HTML report
      await testInfo.attach("response.json", {
        body: JSON.stringify({
          status: actual,
          headers: respHeaders,
          body: respBody,
        }, null, 2),
        contentType: "application/json",
      });

      const result = classifyResponse(actual, tc.expectedStatus);
      results.push({
        id: tc.id,
        name: tc.name,
        category: tc.category,
        expectedStatus: tc.expectedStatus,
        actualStatus: actual,
        result,
        risk: tc.risk,
        reason: tc.reason,
        request: {
          method: METHOD,
          url: \`\${BASE_URL}\${ENDPOINT}\`,
          headers: redactHeaders(headers),
          body: requestBody ?? null,
        },
        response: {
          status: actual,
          headers: respHeaders,
          body: respBody,
        },
      });

      expect.soft(actual, \`Expected \${tc.expectedStatus} for "\${tc.name}", got \${actual}\`).toBe(tc.expectedStatus);

      await ctx.dispose();
    });
  }

  test.afterAll(async () => {
    const passed = results.filter(r => r.result === "pass").length;
    const failed = results.length - passed;
    // eslint-disable-next-line no-console
    console.log(\`\\n=== API TestForge summary ===\\nTotal: \${results.length} | Passed: \${passed} | Failed: \${failed}\`);

    try {
      const reportDir = path.resolve(process.cwd(), "test-results");
      if (!fs.existsSync(reportDir)) fs.mkdirSync(reportDir, { recursive: true });
      fs.writeFileSync(
        path.join(reportDir, "api-testforge-report.json"),
        JSON.stringify({ generatedAt: new Date().toISOString(), totals: { total: results.length, passed, failed }, results }, null, 2),
      );
    } catch (err) {
      // eslint-disable-next-line no-console
      console.warn("Could not write report:", err);
    }
  });
});
`;
}

export function buildEnvExample(config: RequestConfig): string {
  const tokenEnv = config.auth.envVarName || "API_TOKEN";
  const needToken = config.auth.mode !== "none";
  return `BASE_URL=${config.baseUrl}\n${needToken ? `${tokenEnv}=your_token_here\n` : ""}`;
}
